name: DBT CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install sqlfluff
      run: pip install sqlfluff

    - name: Lint SQL files
      run: sqlfluff lint models --dialect ansi

  dbt-run:
    needs: lint-sql
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dbt
      run: pip install dbt

    - name: Run dbt
      run: dbt run

